version: '3.8'

services:
    php:
        build:
            context: '.'
            dockerfile: 'docker/php/Dockerfile'
        ports:
            - 8090:80
        restart: always
        volumes:
            -  ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./:/var/www/html:rw
            - ./docker/php/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
            - ./docker/php/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
            - ./docker/php/logs/:/var/log/apache2/:rw
        networks:
            - app-network
    db:
        image: mariadb
        restart: always
        hostname: "db"
        container_name: "db"
        ports:
            - 3326:3306
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - app-network
    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
    #     networks:
    #         - app-network
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
        networks:
            - app-network
volumes:
    mysql:

networks:
    app-network:
        driver: bridge
